スクリプトは 廿十七年三月十三日 (週一) 廿時58分45秒
 に開始しました]0;yoyopig@yoyopig-VirtualBox: ~/デスクトップ/lab1[01;32myoyopig@yoyopig-VirtualBox[00m:[01;34m~/デスクトップ/lab1[00m$ whoami;pwd
yoyopig
/home/yoyopig/デスクトップ/lab1
]0;yoyopig@yoyopig-VirtualBox: ~/デスクトップ/lab1[01;32myoyopig@yoyopig-VirtualBox[00m:[01;34m~/デスクトップ/lab1[00m$ git config -l
user.email=yoyosuperpig@gmail.com
user.name=YOYOPIG
core.editor=vim
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=https://github.com/YOYOPIG/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;yoyopig@yoyopig-VirtualBox: ~/デスクトップ/lab1[01;32myoyopig@yoyopig-VirtualBox[00m:[01;34m~/デスクトップ/lab1[00m$ git clone https://github.com/YOY OPIG/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
]0;yoyopig@yoyopig-VirtualBox: ~/デスクトップ/lab1[01;32myoyopig@yoyopig-VirtualBox[00m:[01;34m~/デスクトップ/lab1[00m$ exit

スクリプトは 廿十七年三月十三日 (週一) 廿一時〇分廿七秒
 に終了しました